QuickAI.UI/Models/Rating.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace QuickAI.UI.Models
{
    public class Rating
    {
        public int HumanRating { get; set; }
        public int NeuralNetwork { get; set; }
        public string Notes { get; set; }
    }
}

QuickAI.UI/Models/Tweet.cs
using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
namespace QuickAI.UI.Models
{
    public class Tweet
    {
        [BsonId] public ObjectId Id { get; set; }
        [BsonElement("Date")] public DateTime Date { get; set; }
        [BsonElement("Symbol")] public string Symbol { get; set; }
        [BsonElement("Id_Tweet")] public Int64 Id_Tweet { get; set; }
        [BsonElement("Text")] public string Text { get; set; }
        [BsonElement("ID_User")] public Int64 ID_User { get; set; }
        [BsonElement("ID_Name")] public string User_Name { get; set; }
        [BsonElement("Portal")] public string Portal { get; set; }
        [BsonElement("Human_rating")] public string Human_rating { get; set; }
        [BsonElement("Neural_rating")] public string Neural_rating { get; set; }
        [BsonElement("Date_Inserted")] public DateTime Date_Inserted { get; set; }
    }
}

QuickAI.UI/Controllers/TweetInformationController.cs
using System.Linq;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using QuickAI.UI.Models;
using  PagedList;
using System;
using System.Globalization;
namespace QuickAI.UI.Controllers
{
    public class TweetInformationController : Controller
    {
        public MongoContext MongoContext;

        public TweetInformationController()
        {
            MongoContext = new MongoContext();
        }

        [HttpGet]
        public ActionResult Index(int? page)
        {
            var documents = MongoContext.Collection.Find(new BsonDocument()).ToList();

            ViewBag.DateToday = DateTime.Now.ToLongDateString();
            return View(documents.ToList().ToPagedList(page ?? 1, documents.Count));
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            MongoContext.Collection.DeleteOne(Builders<Tweet>.Filter.Eq("_id", ObjectId.Parse(id)));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Insert(string Human_rating, string id)
        {
            var filter = (Builders<Tweet>.Filter.Eq("_id", ObjectId.Parse(id)));

            MongoContext.Collection.UpdateOne(
                filter,
                Builders<Tweet>.Update
                    .Set("Human_rating", Human_rating));

            return Content("Inserted to Database");
        }

        [HttpGet]
        public ActionResult Filter(string from, string to, int? page)
        {
            const string format_date = "T00:00:00.000Z";
            /*returned index if both date are null */
            if ((from == "" && to == "") || (to != "" && from == ""))
            {
                return RedirectToAction("Index");
            }

            if (to == "" && from != null)
            {
                DateTime d_from;
                string link = from + format_date;
                if (DateTime.TryParseExact(link, "yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture,
                    DateTimeStyles.None, out d_from))
                {
                    //    var filtered_to = MongoContext.Collection.Find(x => x.Date_Inserted == d_from).ToList();
                    var query = MongoContext.Collection.AsQueryable().Where(x => x.Date_Inserted == d_from);
                    return View("Index", query.ToPagedList(page ?? 1, query.Count()));
                }
                else
                {
                    return Content("Cannot format this Date.");
                }
            }
            else
            {
                string link = from + format_date;
                DateTime d_from, d_to;
                string link_ = to + format_date;

                if (DateTime.TryParseExact(link, "yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture,
                    DateTimeStyles.None, out d_from))
                {
                    if (DateTime.TryParseExact(link_, "yyyy-MM-ddTHH:mm:ss.fffZ", CultureInfo.InvariantCulture,
                        DateTimeStyles.None, out d_to))
                    {
                        var filtered_date = MongoContext.Collection.AsQueryable()
                            .Where(x => x.Date_Inserted >= d_from && x.Date_Inserted <= d_to);
                        return View("Index", filtered_date.ToPagedList(page ?? 1, filtered_date.Count()));
                    }
                    else
                    {
                        var filtered_to = MongoContext.Collection.AsQueryable().Where(x => x.Date_Inserted == d_from)
                            .ToList();
                        return View("Index", filtered_to.ToPagedList(page ?? 1, filtered_to.Count));
                    }
                }
                else return Content("Cannot format this Date.");
            }

        }
        [HttpGet]
        public ActionResult Refresh()
        {
            return RedirectToAction("Index");
        }
    }
}

QuickAI.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    @*<link href="http://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />*@
    <link href="~/Scripts/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    @*<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>*@
    <script src="~/Scripts/jquery.dataTables2.min.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <link href="~/Content/PagedList.css" rel="stylesheet" />
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>
</body>
</html>

QuickAI.UI/Views/TweetInformation/Index.cshtml
@using System.Web.UI.WebControls
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<QuickAI.UI.Models.Tweet>
@{
    ViewBag.Title = "Database Content";
}
<h2>
    Database QuickAI
</h2>
<div>
    <a>
        @Model.Count() revievs from Database.
        @ViewBag.DateToday
    </a>
</div>
<legend>Search by date</legend>
@using (Html.BeginForm("Filter", "TweetInformation", FormMethod.Get))
{
    <div id="name">
         <span class="text-capitalize">From : </span><input type="text" name="from" class="glyphicon-search" value="" placeholder="YY-MM-DD (requiere)" Required />
           <span>To : </span><input type="text" name="to" value="" placeholder="YY-MM-DD  (optional)" />
        <input type="submit" name="name" value="Filter" />
     </div>
}

@using (Html.BeginForm("Refresh", "TweetInformation", FormMethod.Get))
{
    <input type="submit" value="Refresh" name="Refresh" id="Refresh" class="btn btn-block btn-primary" style="width:auto" />
}
<button value="Zapisz" id="saveBtn" class="btn btn-block btn-success" style="width:10%">Insert</button>
<table id="tweetTable" class="display" style="width:100%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Symbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Id_Tweet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().ID_User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().User_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Portal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Human_rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Neural_rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Date_Inserted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Symbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id_Tweet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Text)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ID_User)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Portal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Human_rating)
                    @Html.TextBox("Human_rating" + item.Id, item.Human_rating, new { @class = "Human_rating", @PlaceHolder = "Rate", @data_id = item.Id })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Neural_rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Inserted)
                </td>
                <td>
                    <a href="@Url.Action("Delete", "TweetInformation",
                              new
                              {
                                  id = item.Id
                              })" class="btn btn-danger" onclick="return confirm('This will result in deletion from the database\r\n.')">Delete</a>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#tweetTable').DataTable();
    });

    $("#saveBtn").on("click", function () {
        var komunikat = '';
        $(".Human_rating").each(function () {
            var id = $(this).attr("data-id");

            $.ajax({
                url: "@Url.Action("Insert")",
                data: {
                    id: id,
                    Human_rating: $("#Human_rating" + id).val()
                },
                success: function (result) {
                    //alert(result);
                },
                error: function () {
                    //alert('Nie udało się zapisać! '+id);
                    komunikat += 'Error ' + id;
                }
            });
        });
        alert('Inserted to Database ' + komunikat);
    });
</script>